#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE INSPIRE_INGEST;
    GRANT ALL PRIVILEGES ON DATABASE INSPIRE_INGEST TO postgres;
EOSQL

